### ISSUE TITLE
GMC Progress Tracker

### ISSUE THREAD

**Issue by avanwinkle** [missionpinball/mpf-gmc#1]
The following outline covers the core functionality that the Godot MC will need to be a usable replacement for the old Kivy MC. 

### Core
- [x] Godot Plugin with custom classes and singletons
- [x] BCP Interface to communicate with MPF
- [x] Keyboard input support for events and switches
- [x] Basic logging support
- [ ] Logging levels with verbose and production flags

### Slides
- [x] [MPF] SlidePlayer plugin
- [x] Base class for MPFSlide
- [x] User-generated slides with default fallbacks
- [x] Play slides from *slides_play* event
- [x] Update slides from `action: update` arg
- [x] Remove slides from `action: remove` arg
- [ ] Remove slides from `expire: <secs>` arg
- [x] Remove slides from *slides_clear* event
- [ ] Support for `action: method` calls to slide methods
- [x] Stack slides by priority
- [x] Target slides to a specific display
- [ ] Delay clearing of only slide until next one arrives
- [ ] Transitions for slide entry/exit

### Widgets
- [ ] [MPF] WidgetPlayer plugin
- [ ] Base class for MPFWidget
- [ ] Play widgets from *widgets_play* event
- [ ] Update widgets from `action: update` arg
- [ ] Remove widgets from `action: remove` arg
- [ ] Remove widgets from `expire: <secs>` arg
- [ ] Remove widgets from *widgets_clear* event
- [ ] Support for `action: method` calls to widget methods
- [ ] Target widgets to a specific display
- [ ] Target widgets to a specific slide

### Variables
- [x] Base class for MPFVariable
- [x] Text nodes for player, machine, and event arg values
- [x] Options for comma separation, minimum digits, and initialize empty
- [x] Custom text formatting with injection of variable value
- [x] Dynamic values from vars, events, and event settings
- [x] Update text on player variable changes
- [x] Update text on `action: update` arg
- [ ] Base class for MPFRichTextVariable

### Window
- [x] Base class for MPFWindow
- [x] Pass slide events to target display
- [ ] Support multiple displays/monitors
- [ ] Flag for fullscreen mode

### Sounds
- [ ] [MPF] SoundPlayer plugin
- [ ] Base class for SoundPlayer
- [ ] Playback of sounds from *sounds_play* event
- [ ] Update sound loops from `action: update` arg
- [ ] Stop sounds from `action: stop` arg
- [ ] Stop sounds from *sounds_clear* event
- [ ] Dynamic allocation of tracks and channels from config
- [ ] Track types for solo, simultaneous, and sequential
- [ ] Synchronize sound loops and loop-based transitions
- [ ] Automatic cross-fading of solo tracks
- [ ] Events posted at marker times
- [ ] Max queue time

### Editor Integration
- [x] Editor plugin with custom classes
- [ ] Custom icons for custom classes
- [ ] Spawn MPF with project launch
- [ ] Configure launch flags via UI tab
- [ ] Render MPF log output in UI tab

### Usability
- [x] Sample project with demos for all features
- [ ] Installation & Setup guide
- [ ] Tutorials for common scenarios

**Comment by avanwinkle** [comment]
## Future Features (post MVP)

### Slides
- [ ] Delay clearing of only slide until next one arrives
- [ ] Transitions for slide entry/exit
- [ ] Queue player for sequential playback

### Variables
- [ ] Base class for MPFRichTextVariable
- [ ] Parse RichText to substitute multiple MPF values

### Editor Integration
- [ ] Custom icons for custom classes
- [ ] Spawn MPF with project launch
- [ ] Configure launch flags via UI tab
- [ ] Render MPF log output in UI tab

**Comment by ecurtz** [comment]
Random links on various in progress items:
Logging: https://godotengine.org/asset-library/asset/2381
Variable formatting: https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_format_string.html
Fullscreen display: https://docs.godotengine.org/en/latest/classes/class_displayserver.html#class-displayserver-method-window-set-mode
Sound mixing: https://github.com/godotengine/godot-proposals/issues/3286
